//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamWorkManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseDtl
    {
        public byte Id { get; set; }
        public string ReleaseName { get; set; }
        public string ReleaseDesc { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<bool> IsReleaseComplete { get; set; }
    }
}
