//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamWorkManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamMgmtDBEntities : DbContext
    {
        public TeamMgmtDBEntities()
            : base("name=TeamMgmtDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LkpRole> LkpRoles { get; set; }
        public DbSet<LkpStatu> LkpStatus { get; set; }
        public DbSet<ReleaseDtl> ReleaseDtls { get; set; }
        public DbSet<TeamMember> TeamMembers { get; set; }
        public DbSet<WorkHistory> WorkHistories { get; set; }
    }
}
